/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bdx.bwallet.tools.ui;

import com.bdx.bwallet.tools.core.utils.DeterministicKeyUtils;
import com.bdx.bwallet.tools.ui.utils.BrowserUtils;
import com.bdx.bwallet.tools.ui.utils.LabelUtils;
import com.bdx.bwallet.tools.ui.utils.QRCodes;
import com.google.common.base.Optional;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.image.BufferedImage;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import org.bitcoinj.crypto.ChildNumber;
import org.bitcoinj.crypto.DeterministicKey;
import org.bitcoinj.params.MainNetParams;

/**
 *
 * @author Administrator
 */
public class AddressDetailsDialog extends javax.swing.JDialog {

    private String address;

    /**
     * Creates new form AddressDetailsDialog
     */
    public AddressDetailsDialog(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qrCodePanel = new javax.swing.JPanel();
        addressLabel = new javax.swing.JLabel();
        pathLabel = new javax.swing.JLabel();
        xpubLabel = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        xpubTextArea = new javax.swing.JTextArea();
        pathContentLabel = new javax.swing.JLabel();
        copyAddressButton = new javax.swing.JButton();
        copyXpubButton = new javax.swing.JButton();
        viewBlockchainButton = new javax.swing.JButton();
        viewBlockmetaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Address Details");
        setResizable(false);

        javax.swing.GroupLayout qrCodePanelLayout = new javax.swing.GroupLayout(qrCodePanel);
        qrCodePanel.setLayout(qrCodePanelLayout);
        qrCodePanelLayout.setHorizontalGroup(
            qrCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        qrCodePanelLayout.setVerticalGroup(
            qrCodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        addressLabel.setText("Address");

        pathLabel.setText("Path");

        xpubLabel.setText("Xpub");

        addressTextField.setEditable(false);

        xpubTextArea.setEditable(false);
        xpubTextArea.setColumns(20);
        xpubTextArea.setLineWrap(true);
        xpubTextArea.setRows(5);
        jScrollPane1.setViewportView(xpubTextArea);

        pathContentLabel.setText("m/44'/0'/0'/0/0");

        copyAddressButton.setText("Copy");
        copyAddressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyAddressButtonActionPerformed(evt);
            }
        });

        copyXpubButton.setText("Copy");
        copyXpubButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyXpubButtonActionPerformed(evt);
            }
        });

        viewBlockchainButton.setText("View at blockchain.info");
        viewBlockchainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBlockchainButtonActionPerformed(evt);
            }
        });

        viewBlockmetaButton.setText("View at blockmeta.com");
        viewBlockmetaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBlockmetaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewBlockchainButton, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(qrCodePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(xpubLabel)
                                    .addComponent(pathLabel))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pathContentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(copyAddressButton)
                            .addComponent(copyXpubButton)))
                    .addComponent(viewBlockmetaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(qrCodePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addressLabel)
                            .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(copyAddressButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pathLabel)
                            .addComponent(pathContentLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(xpubLabel)
                                    .addComponent(copyXpubButton))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewBlockchainButton)
                    .addComponent(viewBlockmetaButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void copyAddressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyAddressButtonActionPerformed
        String text = addressTextField.getText();
        StringSelection selection = new StringSelection(text);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(selection, selection);
    }//GEN-LAST:event_copyAddressButtonActionPerformed

    private void copyXpubButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyXpubButtonActionPerformed
        String text = xpubTextArea.getText();
        StringSelection selection = new StringSelection(text);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(selection, selection);
    }//GEN-LAST:event_copyXpubButtonActionPerformed

    private void viewBlockchainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBlockchainButtonActionPerformed
        try {
            BrowserUtils.openWebpage(new URL("https://blockchain.info/address/" + address));
        } catch (MalformedURLException ex) {
            Logger.getLogger(AddressDetailsDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewBlockchainButtonActionPerformed

    private void viewBlockmetaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBlockmetaButtonActionPerformed
        try {
            BrowserUtils.openWebpage(new URL("http://blockmeta.com/address/" + address));
        } catch (MalformedURLException ex) {
            Logger.getLogger(AddressDetailsDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewBlockmetaButtonActionPerformed

    public void init(DeterministicKey deterministicKey) {
        address = deterministicKey.toAddress(MainNetParams.get()).toString();

        xpubTextArea.setText(deterministicKey.serializePubB58());
        addressTextField.setText(address);
        
        String path = "m/44'/0'";
        for (ChildNumber childNumber : deterministicKey.getPath()) {
            path = path + "/" + childNumber.num();
            if (childNumber.isHardened())
                path = path + "'";
        }
        pathContentLabel.setText(path);
        
        Optional<BufferedImage> qrCodeImage = QRCodes.generateQRCode(address, 2);
        JLabel imageLabel = LabelUtils.newImageLabel(qrCodeImage);
        imageLabel.setSize(180, 180);
        qrCodePanel.removeAll();
        qrCodePanel.add(imageLabel);
        qrCodePanel.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddressDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddressDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddressDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddressDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddressDetailsDialog dialog = new AddressDetailsDialog(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JButton copyAddressButton;
    private javax.swing.JButton copyXpubButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pathContentLabel;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JPanel qrCodePanel;
    private javax.swing.JButton viewBlockchainButton;
    private javax.swing.JButton viewBlockmetaButton;
    private javax.swing.JLabel xpubLabel;
    private javax.swing.JTextArea xpubTextArea;
    // End of variables declaration//GEN-END:variables
}
