/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bdx.bwallet.tools.ui;

import com.bdx.bwallet.protobuf.BWalletMessage;
import com.bdx.bwallet.tools.controllers.MainController;
import com.bdx.bwallet.tools.core.events.HardwareWalletEvent;
import com.bdx.bwallet.tools.core.events.HardwareWalletEvents;
import com.bdx.bwallet.tools.core.events.MessageEvent;
import com.bdx.bwallet.tools.core.events.MessageEventType;
import com.bdx.bwallet.tools.core.events.MessageEvents;
import com.bdx.bwallet.tools.model.Device;
import com.bdx.bwallet.tools.model.Language;
import com.google.common.eventbus.Subscribe;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import org.hid4java.HidDevice;

/**
 *
 * @author Administrator
 */
public class CreateWalletDialog extends javax.swing.JDialog implements WindowListener {

    private MainController mainController;

    private JDialog messageDialog;

    private Device device;

    private boolean recoveryStarted = false;
    private int recoveryWords = 0;
    private int recoveryWordsDone = 0;
    private int recoveryCurrentWord = 1;

    /**
     * Creates new form CreateWalletDialog
     */
    public CreateWalletDialog(java.awt.Frame parent, boolean modal, MainController mainController, Device device) {
        super(parent, modal);
        initComponents();

        DefaultComboBoxModel languageComboBoxModel = (DefaultComboBoxModel) languageComboBox.getModel();
        languageComboBoxModel.removeAllElements();
        languageComboBoxModel.addElement(new Language("english", "English"));
        languageComboBoxModel.addElement(new Language("chinese", "中文"));

        JOptionPane messagePanel = new JOptionPane("Please confirm on your device.", JOptionPane.INFORMATION_MESSAGE,
                JOptionPane.DEFAULT_OPTION, null,
                new Object[]{}, null);
        messageDialog = messagePanel.createDialog(null, "Device Setup");
        messageDialog.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
        messageDialog.setSize(670, 150);
        messageDialog.setLocationRelativeTo(null);
        messageDialog.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e) {
                System.out.println("windowClosing");
                CreateWalletDialog.this.mainController.cancel();
            }
        });

        this.mainController = mainController;
        this.device = device;

        this.addWindowListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basicPanel = new javax.swing.JPanel();
        labelLabel = new javax.swing.JLabel();
        languageLabel = new javax.swing.JLabel();
        labelTextField = new javax.swing.JTextField();
        languageComboBox = new javax.swing.JComboBox();
        continueButton = new javax.swing.JButton();
        advancedPanel = new javax.swing.JPanel();
        lengthLabel = new javax.swing.JLabel();
        lengthSlider = new javax.swing.JSlider();
        len12Label = new javax.swing.JLabel();
        len18Label = new javax.swing.JLabel();
        len24Label = new javax.swing.JLabel();
        pinLabel = new javax.swing.JLabel();
        passphraseLabel = new javax.swing.JLabel();
        pinCheckBox = new javax.swing.JCheckBox();
        passphraseCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Device Setup");
        setResizable(false);

        basicPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(" Basic settings "));

        labelLabel.setText("Device label");

        languageLabel.setText("Device language");

        labelTextField.setText("My BWallet");

        languageComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "English", "中文" }));
        languageComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout basicPanelLayout = new javax.swing.GroupLayout(basicPanel);
        basicPanel.setLayout(basicPanelLayout);
        basicPanelLayout.setHorizontalGroup(
            basicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(languageComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(languageLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                    .addComponent(labelTextField))
                .addContainerGap())
        );
        basicPanelLayout.setVerticalGroup(
            basicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(languageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(languageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        continueButton.setText("Continue");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        advancedPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(" Advanced settings "));

        lengthLabel.setText("Recovery seed length");

        lengthSlider.setMaximum(24);
        lengthSlider.setMinimum(12);
        lengthSlider.setMinorTickSpacing(6);
        lengthSlider.setPaintTicks(true);
        lengthSlider.setSnapToTicks(true);

        len12Label.setText("12 words");
        len12Label.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        len18Label.setText("18 words");
        len18Label.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        len24Label.setText("24 words");
        len24Label.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        pinLabel.setText("PIN protection");

        passphraseLabel.setText("Additional passphrase encryption");

        pinCheckBox.setSelected(true);
        pinCheckBox.setText("Enable PIN protection");
        pinCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinCheckBoxActionPerformed(evt);
            }
        });

        passphraseCheckBox.setText("Enable passphrase encryption");
        passphraseCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passphraseCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout advancedPanelLayout = new javax.swing.GroupLayout(advancedPanel);
        advancedPanel.setLayout(advancedPanelLayout);
        advancedPanelLayout.setHorizontalGroup(
            advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advancedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(advancedPanelLayout.createSequentialGroup()
                        .addComponent(len12Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(len18Label)
                        .addGap(203, 203, 203)
                        .addComponent(len24Label))
                    .addGroup(advancedPanelLayout.createSequentialGroup()
                        .addGroup(advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passphraseCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pinCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lengthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lengthSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passphraseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        advancedPanelLayout.setVerticalGroup(
            advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advancedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lengthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lengthSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(len24Label)
                        .addComponent(len18Label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(len12Label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pinCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passphraseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passphraseCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(basicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(advancedPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(continueButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(basicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(advancedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(continueButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void languageComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languageComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_languageComboBoxActionPerformed

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        if (device != null) {
            Language language = (Language) ((DefaultComboBoxModel) languageComboBox.getModel()).getSelectedItem();
            String label = labelTextField.getText();
            boolean pinProtection = pinCheckBox.isSelected();
            boolean passphraseProtection = passphraseCheckBox.isSelected();
            int seedLength = lengthSlider.getValue();

            System.out.println(language.getValue());
            System.out.println(label);
            System.out.println(pinProtection);
            System.out.println(passphraseProtection);
            System.out.println((seedLength / 6) * 64);
            
            recoveryStarted = false;
            recoveryWords = seedLength;
            recoveryWordsDone = 0;
            recoveryCurrentWord = 1;

            mainController.createWallet(device, language.getValue(), label, false, pinProtection, passphraseProtection, (seedLength / 6) * 64);
        } else {
            JOptionPane.showMessageDialog(null, "Device detached");
        }
    }//GEN-LAST:event_continueButtonActionPerformed

    private void pinCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinCheckBoxActionPerformed

    private void passphraseCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passphraseCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passphraseCheckBoxActionPerformed

    protected String ordinal(int i) {
        String[] sufixes = new String[]{"th", "st", "nd", "rd", "th", "th", "th", "th", "th", "th"};
        switch (i % 100) {
            case 11:
            case 12:
            case 13:
                return i + "th";
            default:
                return i + sufixes[i % 10];
        }
    }

    @Subscribe
    public void onHardwareWalletEvent(HardwareWalletEvent event) {
        System.out.println(event.getEventType());
        String msg = "";
        switch (event.getEventType()) {
            case SHOW_BUTTON_PRESS:
                if (!recoveryStarted) {
                    // First write
                    recoveryStarted = true;
                    msg = "We will now show you " + recoveryWords + " words that will allow you to recover your accounts in case you lose your device. \r\nPlease write down all these words carefully.\r\n\r\n";
                    msg += "Please write down the " + ordinal(recoveryCurrentWord) + " word of your recovery seed.";
                } else {
                    recoveryWordsDone = recoveryWordsDone + 1;
                    recoveryCurrentWord = recoveryCurrentWord + 1;
                    if (recoveryWordsDone < recoveryWords) {
                        // Write
                        msg = "Please write down the " + ordinal(recoveryCurrentWord) + " word of your recovery seed.";
                    } else if (recoveryWordsDone == recoveryWords) {
                        // First check
                        recoveryCurrentWord = 1;
                        msg = "We will now show you the " + recoveryWords + " words again. \r\nPlease check carefully that you wrote them down correctly.\r\n\r\n";
                        msg += "Please check the " + ordinal(recoveryCurrentWord) + " word of your recovery seed.";
                    } else if (recoveryWordsDone < 2 * recoveryWords - 1) {
                        // Check
                        msg = "Please check the " + ordinal(recoveryCurrentWord) + " word of your recovery seed.";
                    } else {
                        // Last check
                        msg = "Please check the " + ordinal(recoveryCurrentWord) + " word of your recovery seed.";
                    }
                }
                ((JOptionPane)messageDialog.getContentPane().getComponent(0)).setMessage(msg);
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        messageDialog.setVisible(true);
                    }
                });
                break;
            case SHOW_PIN_ENTRY:
                PINEntryDialog pinEntryDialog = new PINEntryDialog(this, true);
                pinEntryDialog.setLocationRelativeTo(null);
                if (event.getMessage().isPresent()) {
                    BWalletMessage.PinMatrixRequest pinRequest = (BWalletMessage.PinMatrixRequest) event.getMessage().get();
                    msg = "Please enter PIN:";
                    if ("PinMatrixRequestType_Current".equals(pinRequest.getType().name())) {
                        msg = "Please enter current PIN:";
                    } else if ("PinMatrixRequestType_NewFirst".equals(pinRequest.getType().name())) {
                        msg = "Please enter new PIN:";
                    } else if ("PinMatrixRequestType_NewSecond".equals(pinRequest.getType().name())) {
                        msg = "Please re-enter new PIN:";
                    }
                    pinEntryDialog.setPinTitle(msg);
                }
                pinEntryDialog.setVisible(true);
                System.out.println("pin - " + pinEntryDialog.isCancel());
                if (pinEntryDialog.isCancel()) {
                    mainController.cancel();
                } else {
                    String pin = pinEntryDialog.getPin();
                    System.out.println("pin : " + pin);
                    mainController.providePin(pin);
                }
                break;
            case PROVIDE_ENTROPY:
                byte[] entropy = mainController.generateEntropy();
                mainController.provideEntropy(entropy);
                break;
            case SHOW_OPERATION_SUCCEEDED:
                messageDialog.setVisible(false);
                JOptionPane.showMessageDialog(null, "Setup was successful");
                this.dispose();
                break;
            case SHOW_OPERATION_FAILED:
                messageDialog.setVisible(false);
                msg = "Create failed";
                if (event.getMessage().isPresent()) {
                    BWalletMessage.Failure failure = (BWalletMessage.Failure) event.getMessage().get();
                    msg = msg + " : " + failure.getMessage();
                }
                JOptionPane.showMessageDialog(null, msg);
                break;
            default:
                break;
        }
    }

    @Subscribe
    public void onMessageEvent(MessageEvent event) {
        if (event.getEventType() == MessageEventType.DEVICE_DETACHED) {
            HidDevice hidDevice = event.getDevice().get();
            if (hidDevice.getPath() != null && hidDevice.getPath().equals(device.getPath())) {
                device = null;
                messageDialog.setVisible(false);
                JOptionPane.showMessageDialog(null, "Device detached");
            }
        }
    }

    @Override
    public void windowOpened(WindowEvent e) {
        HardwareWalletEvents.subscribe(this);
        MessageEvents.subscribe(this);
    }

    @Override
    public void windowClosing(WindowEvent e) {
    }

    @Override
    public void windowClosed(WindowEvent e) {
        HardwareWalletEvents.unsubscribe(this);
        MessageEvents.unsubscribe(this);
    }

    @Override
    public void windowIconified(WindowEvent e) {
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
    }

    @Override
    public void windowActivated(WindowEvent e) {
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateWalletDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateWalletDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateWalletDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateWalletDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateWalletDialog dialog = new CreateWalletDialog(new javax.swing.JFrame(), true, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel advancedPanel;
    private javax.swing.JPanel basicPanel;
    private javax.swing.JButton continueButton;
    private javax.swing.JLabel labelLabel;
    private javax.swing.JTextField labelTextField;
    private javax.swing.JComboBox languageComboBox;
    private javax.swing.JLabel languageLabel;
    private javax.swing.JLabel len12Label;
    private javax.swing.JLabel len18Label;
    private javax.swing.JLabel len24Label;
    private javax.swing.JLabel lengthLabel;
    private javax.swing.JSlider lengthSlider;
    private javax.swing.JCheckBox passphraseCheckBox;
    private javax.swing.JLabel passphraseLabel;
    private javax.swing.JCheckBox pinCheckBox;
    private javax.swing.JLabel pinLabel;
    // End of variables declaration//GEN-END:variables
}
