/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bdx.bwallet.tools.ui;

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.Arrays;
import java.util.ResourceBundle;

/**
 *
 * @author Administrator
 */
public class PINEntryDialog extends javax.swing.JDialog implements WindowListener {

    private ResourceBundle bundle;

    private String pin = "";

    private boolean cancel = false;

    /**
     * Creates new form PINEntryDialog
     */
    public PINEntryDialog(java.awt.Dialog parent, boolean modal, ResourceBundle bundle) {
        super(parent, modal);
        initComponents();
        this.addWindowListener(this);
        this.bundle = bundle;
        applyResourceBundle();
    }

    public void applyResourceBundle() {
        lookDeviceLabel.setText(bundle.getString("PINEntryDialog.lookDeviceLabel.text")); 
        titleLabel.setText(bundle.getString("PINEntryDialog.titleLabel.text")); 
        enterButton.setText(bundle.getString("PINEntryDialog.enterButton.text")); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pin5Button = new javax.swing.JButton();
        pin4Button = new javax.swing.JButton();
        pin3Button = new javax.swing.JButton();
        pin2Button = new javax.swing.JButton();
        pin1Button = new javax.swing.JButton();
        pinPasswordField = new javax.swing.JPasswordField();
        backspaceButton = new javax.swing.JButton();
        lookDeviceLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        pin9Button = new javax.swing.JButton();
        pin6Button = new javax.swing.JButton();
        pin8Button = new javax.swing.JButton();
        pin7Button = new javax.swing.JButton();
        verificationLabel = new javax.swing.JLabel();
        enterButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pin5Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        pin5Button.setText("*");
        pin5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pin5ButtonActionPerformed(evt);
            }
        });

        pin4Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        pin4Button.setText("*");
        pin4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pin4ButtonActionPerformed(evt);
            }
        });

        pin3Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        pin3Button.setText("*");
        pin3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pin3ButtonActionPerformed(evt);
            }
        });

        pin2Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        pin2Button.setText("*");
        pin2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pin2ButtonActionPerformed(evt);
            }
        });

        pin1Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        pin1Button.setText("*");
        pin1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pin1ButtonActionPerformed(evt);
            }
        });

        pinPasswordField.setEditable(false);

        backspaceButton.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        backspaceButton.setText("←");
        backspaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceButtonActionPerformed(evt);
            }
        });

        lookDeviceLabel.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lookDeviceLabel.setForeground(new java.awt.Color(255, 0, 0));
        lookDeviceLabel.setText("Look at the device for number positions.");

        titleLabel.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        titleLabel.setText("Please enter PIN:");

        pin9Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        pin9Button.setText("*");
        pin9Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pin9ButtonActionPerformed(evt);
            }
        });

        pin6Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        pin6Button.setText("*");
        pin6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pin6ButtonActionPerformed(evt);
            }
        });

        pin8Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        pin8Button.setText("*");
        pin8Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pin8ButtonActionPerformed(evt);
            }
        });

        pin7Button.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        pin7Button.setText("*");
        pin7Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pin7ButtonActionPerformed(evt);
            }
        });

        enterButton.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        enterButton.setText("Enter");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pin1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pin7Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pin4Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(pin2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(pin3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pin5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pin8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pin9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pin6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lookDeviceLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(verificationLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(pinPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(backspaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lookDeviceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pin7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pin8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pin9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pin4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pin5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pin6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pin1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pin2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pin3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backspaceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pinPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(verificationLabel)
                .addGap(18, 18, 18)
                .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pin5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pin5ButtonActionPerformed
        pinMatrixClicked(5);
    }//GEN-LAST:event_pin5ButtonActionPerformed

    private void pin4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pin4ButtonActionPerformed
        pinMatrixClicked(4);
    }//GEN-LAST:event_pin4ButtonActionPerformed

    private void pin3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pin3ButtonActionPerformed
        pinMatrixClicked(3);
    }//GEN-LAST:event_pin3ButtonActionPerformed

    private void pin2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pin2ButtonActionPerformed
        pinMatrixClicked(2);
    }//GEN-LAST:event_pin2ButtonActionPerformed

    private void pin1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pin1ButtonActionPerformed
        pinMatrixClicked(1);
    }//GEN-LAST:event_pin1ButtonActionPerformed

    private void backspaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceButtonActionPerformed
        char[] pin = pinPasswordField.getPassword();
        if (pin.length > 0) {
            pinPasswordField.setText(new String(Arrays.copyOf(pin, pin.length - 1)));
            if (!enterButton.isEnabled() && !(pinPasswordField.getPassword().length > 9)) {
                enterButton.setEnabled(true);
                verificationLabel.setText("");
            }
            System.out.println(new String(pinPasswordField.getPassword()));
        }
    }//GEN-LAST:event_backspaceButtonActionPerformed

    private void pin9ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pin9ButtonActionPerformed
        pinMatrixClicked(9);
    }//GEN-LAST:event_pin9ButtonActionPerformed

    private void pin6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pin6ButtonActionPerformed
        pinMatrixClicked(6);
    }//GEN-LAST:event_pin6ButtonActionPerformed

    private void pin8ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pin8ButtonActionPerformed
        pinMatrixClicked(8);
    }//GEN-LAST:event_pin8ButtonActionPerformed

    private void pin7ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pin7ButtonActionPerformed
        pinMatrixClicked(7);
    }//GEN-LAST:event_pin7ButtonActionPerformed

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        this.pin = new String(pinPasswordField.getPassword());
        this.cancel = false;
        this.dispose();
    }//GEN-LAST:event_enterButtonActionPerformed

    private void pinMatrixClicked(int number) {
        pinPasswordField.setText(new String(pinPasswordField.getPassword()) + number);
        if (pinPasswordField.getPassword().length > 9) {
            enterButton.setEnabled(false);
            verificationLabel.setText(bundle.getString("PINEntryDialog.verificationLabel.text"));
        }
    }

    public void setPinTitle(String title) {
        titleLabel.setText(title);
    }

    public String getPin() {
        return pin;
    }

    public boolean isCancel() {
        return cancel;
    }

    @Override
    public void windowOpened(WindowEvent e) {
    }

    @Override
    public void windowClosing(WindowEvent e) {
        this.pin = "";
        this.cancel = true;
    }

    @Override
    public void windowClosed(WindowEvent e) {
    }

    @Override
    public void windowIconified(WindowEvent e) {
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
    }

    @Override
    public void windowActivated(WindowEvent e) {
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PINEntryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PINEntryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PINEntryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PINEntryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PINEntryDialog dialog = new PINEntryDialog(new javax.swing.JDialog(), true, ResourceBundle.getBundle("com/bdx/bwallet/tools/ui/Bundle"));
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backspaceButton;
    private javax.swing.JButton enterButton;
    private javax.swing.JLabel lookDeviceLabel;
    private javax.swing.JButton pin1Button;
    private javax.swing.JButton pin2Button;
    private javax.swing.JButton pin3Button;
    private javax.swing.JButton pin4Button;
    private javax.swing.JButton pin5Button;
    private javax.swing.JButton pin6Button;
    private javax.swing.JButton pin7Button;
    private javax.swing.JButton pin8Button;
    private javax.swing.JButton pin9Button;
    private javax.swing.JPasswordField pinPasswordField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel verificationLabel;
    // End of variables declaration//GEN-END:variables
}
